stages:
  - build

release:
  stage: build
  tags:
    - feur-linux
  image: python:3.11.8
  before_script:
    - apt-get update && apt-get install -y zip sshpass
  script:
    - zip -r qtquickdetect.zip . -x "*.git*" -x "*.gitignore" -x "*.gitlab-ci.yml" -x "*tests*" -x "*website*" -x "*gestion_projet*" "*notebooks*"
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_URL "rm -f /var/www/qtquickdetect.feur.live/qtquickdetect.zip"
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no qtquickdetect.zip $SSH_USER@$SSH_URL:/var/www/qtquickdetect.feur.live/
  only:
    - main

update_website:
  stage: build
  image: debian:latest
  tags:
    - feur-linux
  before_script:
    - apt-get update && apt-get install -y sshpass
  script:
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no ./website/index.html $SSH_USER@$SSH_URL:/var/www/qtquickdetect.feur.live/index.html
  only:
    - main

test:
  stage: test
  tags:
    - feur-linux
  image: python:3.11.8
  before_script:
    - apt-get update && apt-get install -y zip sshpass
    - python -m pip install --upgrade pip
    - pip install hatch
    - hatch run pip install -r requirements.txt
    - hatch run pip install pytest==8.2.2 pytest-qt==4.4.0
  script:
    - pytest
  only:
    - dev