stages:
  - build
  - test

build_linux:
  stage: build
  image: python:3.11.8
  before_script:
      - apt-get update && apt-get install -y zip
      - pip install -r requirements.txt
  script:
    - pyinstaller qtquickdetect.py --add-data="cfg/ultralytics/default.yaml:ultralytics/cfg" --add-data="ressources:ressources"
  artifacts:
    paths:
      - dist/
  only:
    - main

build_windows:
  stage: build
  tags:
    - saas-windows-medium-amd64
  before_script:
    - choco install python --version 3.11.8 -y -f
    - C:\Python311\python.exe -m ensurepip
    - C:\Python311\python.exe -m pip install --upgrade pip
    - C:\Python311\python.exe -m pip install -r requirements.txt
  script:
    - C:\Python311\python.exe -m pyinstaller qtquickdetect.py --add-data="cfg/ultralytics/default.yaml;ultralytics/cfg" --add-data="ressources;ressources"
  artifacts:
    paths:
      - dist/
  only:
    - main