stages:
  - build
  - test

build_linux:
  stage: build
  tags:
    - feur-linux
  image: python:3.11.8
  before_script:
      - apt-get update && apt-get install -y zip sshpass
      - pip install -r requirements.txt
  script:
    - pyinstaller qtquickdetect.py --add-data="cfg/ultralytics/default.yaml:ultralytics/cfg" --add-data="ressources:ressources"
    - cd dist/
    - zip -r qtquickdetect-linux.zip qtquickdetect/
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_URL "rm -f /var/www/qtquickdetect.feur.live/qtquickdetect-linux.zip"
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no qtquickdetect-linux.zip $SSH_USER@$SSH_URL:/var/www/qtquickdetect.feur.live/
  only:
    - main

build_windows:
  stage: build
  image: tobix/pywine:3.11
  tags:
    - feur-linux
  script:
    - . /opt/mkuserwineprefix
    - wine /opt/wineprefix/drive_c/Python311/Python.exe -v
    - wine /opt/wineprefix/drive_c/Python311/Python.exe -m ensurepip
    - wine /opt/wineprefix/drive_c/Python311/Python.exe -m pip install --upgrade pip
    - wine /opt/wineprefix/drive_c/Python311/Python.exe -m pip install -r requirements.txt
    - wine /opt/wineprefix/drive_c/Python311/Scripts/pyinstaller.exe qtquickdetect.py --add-data="cfg/ultralytics/default.yaml;ultralytics/cfg" --add-data="ressources;ressources"
    - cd dist/
    - zip -r qtquickdetect-windows.zip qtquickdetect/
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_URL "rm -f /var/www/qtquickdetect.feur.live/qtquickdetect-windows.zip"
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no qtquickdetect-windows.zip $SSH_USER@$SSH_URL:/var/www/qtquickdetect.feur.live/
  only:
    - main