stages:
  - build
  - test

build_linux:
  stage: build
  image: python:3.9
  script:
    - pip install pyinstaller
    - pyinstaller qtquickdetect.py --add-data="cfg/ultralytics/default.yaml:ultralytics/cfg" --add-data="ressources:ressources"
  artifacts:
    paths:
      - dist/
  only:
    - main

build_windows:
  stage: build
  tags:
    - saas-windows-medium-amd64
  script:
    - pip install pyinstaller
    - pyinstaller qtquickdetect.py --add-data="cfg\ultralytics\default.yaml;ultralytics\cfg" --add-data="ressources;ressources"
  artifacts:
    paths:
      - dist/
  only:
    - main